package com.modulotech.utilities

const val TOKEN : String = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5naGlhcGQ5MiIsImlkIjoiNjBiNjU4OTgwNWRiNGQ2Mzg2OTI4NGVlIiwiaWF0IjoxNjI3NTY4Mzg1fQ.PmU8Iyomx59SLBic-8ewaa2VuaeDdkgvwmDnUaaQ6LY"